### ISSUE TITLE
Meet a strange problem when I install pymbd

### ISSUE THREAD

**Issue by amseram** [azag0/pymbd#1]
Dear Jan Hermann,
When I install the pymbd via the methods shown in README, I found that there is no lib.py in pymbd folder. Besides of that, when I used "python3 setup.py install" install it, lib.py will be generated. However, when I run "python -m unittest pymbd.tests -v" , I got the results like:
test_basic (pymbd.tests.TestCoulomb) ...    1.0000000000000000        1.0000000000000000
 Coulomb 2-body =   0.10002330336791715
 Coulomb 1-body =   0.31247469913870679
 coul_en =   -5.8346493647400854E-002
ok
test_frequency_grid_15 (pymbd.tests.TestFreqGrid) ... ok
test_frequency_grid_20 (pymbd.tests.TestFreqGrid) ... ok
test_frequency_grid_25 (pymbd.tests.TestFreqGrid) ... ok
test_frequency_grid_30 (pymbd.tests.TestFreqGrid) ... expected failure
test_frequency_grid_35 (pymbd.tests.TestFreqGrid) ... expected failure
test_argon_dimer (pymbd.tests.TestMBD) ...  Initialized a radial integration grid of 15 points.
 Relative quadrature error in C6 of carbon atom: 0.11183025616645637E-008
ok

----------------------------------------------------------------------
Ran 7 tests in 0.032s

OK (expected failures=2)

**Comment by azag0** [comment]
What `pymbd` folder do you mean? If you installed via pip, it shouldn't have created any `pymbd` directory. Pip installs packages in the [site-packages](https://docs.python.org/3/library/site.html) directory, not locally.

And that output is exactly as it should be, the failures are expected, as it says.

**Comment by amseram** [comment]
Sorry for my blur describe.  I mean when I install the pymbd via pip, it will show some error like this:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/lib/python3.6/site-packages/pymbd-0.2-py3.6-linux-x86_64.egg/pymbd/__init__.py",                     line 1, in <module>
    from .pymbd import *
  File "/opt/miniconda3/lib/python3.6/site-packages/pymbd-0.2-py3.6-linux-x86_64.egg/pymbd/pymbd.py", lin                    e 8, in <module>
    from .lib import mbd as _mbd
ModuleNotFoundError: No module named 'pymbd.lib'
. However, I could fix it after I copy the lib.py into the pymbd .

**Comment by amseram** [comment]
I take a pure debian system, and install the miniconda3, and then the problem go away. I think the former problem may caused by my system environment. Thank you for your response
